CREATE TABLE USUARIO(
EMAIL varchar(100) NOT NULL,
USER_NAME varchar(50),
LAST_NAME varchar(100) NOT NULL,
PWD  blob NOT NULL,
COMPANY VARCHAR(150) NOT NULL,
ACTIVE BOOL DEFAULT false,
PRIMARY KEY (EMAIL)
);